# Automatically generated by configure - do not modify
SRC_PATH=/workdir/qemu/roms/vgabios
AS=mips-linux-gnu-as
CCAS=mips-linux-gnu-gcc
CC=mips-linux-gnu-gcc
BCC=bcc
CPP=mips-linux-gnu-gcc -E
OBJCOPY=mips-linux-gnu-objcopy
IASL=iasl
LD=mips-linux-gnu-ld
RANLIB=mips-linux-gnu-ranlib
